### ISSUE TITLE
VSW Magprobe: Probe Housing Missing

### ISSUE THREAD

**Issue by rngSplat** [Annex-Engineering/Annex-Engineering_Other_Printer_Mods#11]
Looks like there are files for the two halves of the carriage, the mount arm, and the mount, but no file for the housing of the probe itself.

I'd love to test this out, if you can add that housing.

**Comment by Annex-Engineering** [comment]
probe is here: https://github.com/Annex-Engineering/Annex-Engineering_Other_Printer_Mods/tree/master/All_Printers/Microswitch_Probe/STLs

mostly bc i havent quite figured out linking in github yet.
